/**
 * Root RTK Query API slice for every Adobe Analytics call the dashboard makes.
 *
 * The browser never talks to Adobe directly. Adobe IMS's OAuth token
 * endpoint doesn't support CORS (it's meant for server-to-server use only),
 * and the client secret can't safely live in a public bundle anyway. So
 * every request here is actually POSTed to a Netlify Function
 * (netlify/functions/reports.js), which holds the secret, exchanges it for a
 * bearer token, and forwards the report request to Adobe. Do not add
 * Authorization/x-api-key/company-id headers back here — the function adds
 * those server-side, and the browser should never see them.
 *
 * Endpoints are defined per dashboard area (traffic/conversion/audience) in
 * ./endpoints and merged in below via RTK Query's injectEndpoints, so each
 * area's file can stay independent while sharing this one base query, cache,
 * and set of tags.
 */
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { injectTrafficEndpoints } from './endpoints/trafficEndpoints';
import { injectConversionEndpoints } from './endpoints/conversionEndpoints';
import { injectAudienceEndpoints } from './endpoints/audienceEndpoints';

const baseApi = createApi({
  reducerPath: 'adobeAnalyticsApi',
  baseQuery: fetchBaseQuery({
    // REACT_APP_API_BASE_URL is the Netlify site hosting the proxy function
    // (see .env.example) — NOT Adobe's API host.
    baseUrl: `${process.env.REACT_APP_API_BASE_URL}/.netlify/functions`,
    prepareHeaders: (headers) => {
      headers.set('Content-Type', 'application/json');
      return headers;
    },
  }),
  tagTypes: ['Traffic', 'Conversion', 'Audience'],
  endpoints: () => ({}),
});

// Order doesn't affect behavior — injectEndpoints just merges each area's
// endpoints onto the shared baseApi.
export const adobeAnalyticsApi = injectAudienceEndpoints(
  injectConversionEndpoints(
    injectTrafficEndpoints(baseApi)
  )
);

// Auto-generated by RTK Query from each endpoint's key (e.g. getTrafficOverview
// -> useGetTrafficOverviewQuery).
//
// Current usage on the live, routed pages (see PageRouter.jsx):
//   - useGetTrafficOverviewQuery : Executive Summary page (via KpiCards) AND
//                                  Traffic Overview page (used directly)
// Not yet wired into any routed page — each lives only inside a feature
// component that nothing currently imports/renders:
//   - useGetTrafficTrendQuery    : features/trafficOverview/TrafficOverview.jsx
//   - useGetConversionFunnelQuery,
//     useGetConversionRateQuery  : features/conversionFunnel/ConversionFunnel.jsx
//                                  (PageRouter's 'funnels' route is still a
//                                  PlaceholderPage)
//   - useGetAudienceBreakdownQuery,
//     useGetAudienceDevicesQuery : features/audienceBreakdown/AudienceBreakdown.jsx
// Update this list when one of those feature components gets mounted on a page.
export const {
  useGetTrafficOverviewQuery,
  useGetTrafficTrendQuery,
  useGetConversionFunnelQuery,
  useGetConversionRateQuery,
  useGetAudienceBreakdownQuery,
  useGetAudienceDevicesQuery,
} = adobeAnalyticsApi;
